CarCommercial/CarCommercial/Models/OglasivackaAgencija.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarCommercial.Models
{
    public class OglasivackaAgencija : Korisnik
    {
        [Display(Name = "# agencije")]
        public int OglasivackaAgencijaID { get; set; }

        [Display(Name = "Naziv tvrtke")]
        [Required(ErrorMessage = "Potrebno je unijeti naziv tvrtke!")]
        public string NazivTvrtke { get; set; }

        [Display(Name = "Sjedište poslovanja tvrtke")]
        [Required(ErrorMessage = "Unesite grad u kojem tvrtka posluje!")]
        public string Sjediste { get; set; }
    }
}

CarCommercial/CarCommercial/Controllers/OglasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CarCommercial.Models;

namespace CarCommercial.Controllers
{
    public class OglasController : Controller
    {
        private CarCommercialContext db = new CarCommercialContext();

        // GET: Oglas
        public ActionResult Index()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("ErrorPage", "Home");
            }
            else
            {
                return View(db.Oglas.ToList());
            }
        }

        // GET: Oglas/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("ErrorPage", "Home");
            }
            else
            {
                if (Session["Status"].ToString() != "agencija")
                {
                    return RedirectToAction("KrivaUloga", "Home");
                }
                else
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    Oglas oglas = db.Oglas.Find(id);
                    if (oglas == null)
                    {
                        return HttpNotFound();
                    }
                    return View(oglas);
                }
            }
        }

        public ActionResult DetailsOpcenito(int? id)
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("ErrorPage", "Home");
            }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Oglas oglas = db.Oglas.Find(id);
                if (oglas == null)
                {
                    return HttpNotFound();
                }
                return View(oglas);
            }
        }

        // GET: Oglas/Create
        public ActionResult Create()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("ErrorPage", "Home");
            }
            else
            {
                if (Session["Status"].ToString() != "agencija")
                {
                    return RedirectToAction("KrivaUloga", "Home");
                }
                else
                {
                    return View();
                }
            }
        }

        // POST: Oglas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OglasID,NaslovOglasa,OpisOglasa,Cijena,PoklopacMotora,Vrata,ZadnjeStaklo,Krov,Korisnik")] Oglas oglas)
        {
            oglas.Korisnik = Session["KorisnickoIme"].ToString();
            if (ModelState.IsValid)
            {
                db.Oglas.Add(oglas);
                db.SaveChanges();
                return RedirectToAction("MojiOglasi");
            }

            return View(oglas);
        }

        // GET: Oglas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("ErrorPage", "Home");
            }
            else
            {
                if (Session["Status"].ToString() != "agencija")
                {
                    return RedirectToAction("KrivaUloga", "Home");
                }
                else
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    Oglas oglas = db.Oglas.Find(id);
                    if (oglas == null)
                    {
                        return HttpNotFound();
                    }
                    return View(oglas);
                }
            }
        }

        // POST: Oglas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OglasID,NaslovOglasa,OpisOglasa,Cijena,PoklopacMotora,Vrata,ZadnjeStaklo,Krov,Korisnik")] Oglas oglas)
        {
            oglas.Korisnik = Session["KorisnickoIme"].ToString();
            if (ModelState.IsValid)
            {
                db.Entry(oglas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("MojiOglasi");
            }
            return View(oglas);
        }

        // GET: Oglas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("ErrorPage", "Home");
            }
            else
            {
                if (Session["Status"].ToString() != "agencija")
                {
                    return RedirectToAction("KrivaUloga", "Home");
                }
                else
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    Oglas oglas = db.Oglas.Find(id);
                    if (oglas == null)
                    {
                        return HttpNotFound();
                    }
                    return View(oglas);
                }
            }
        }

        // POST: Oglas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Oglas oglas = db.Oglas.Find(id);
            db.Oglas.Remove(oglas);
            db.SaveChanges();
            return RedirectToAction("MojiOglasi");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult MojiOglasi()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("ErrorPage", "Home");
            }
            else
            {
                if (Session["Status"].ToString() != "agencija")
                {
                    return RedirectToAction("KrivaUloga", "Home");
                }
                else
                {
                    List<Oglas> lista = new List<Oglas>();
                    foreach (var oglas in db.Oglas)
                    {
                        if (oglas.Korisnik == Session["KorisnickoIme"].ToString())
                        {
                            lista.Add(oglas);
                        }
                    }
                    return View(lista);
                }
            }
        }
    }
}

CarCommercial/CarCommercial/Controllers/OglasivackaAgencijasController.cs
using CarCommercial.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace CarCommercial.Controllers
{
    public class OglasivackaAgencijasController : Controller
    {
        private CarCommercialContext db = new CarCommercialContext();

        // GET: OglasivackaAgencijas
        public ActionResult Index()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("ErrorPage", "Home");
            }
            else
            {
                return View(db.OglasivackaAgencijas.ToList());
            }
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(OglasivackaAgencija oglasivac)
        {
            if (ModelState.IsValid)
            {
                if (ProvjeraKorisnickogImena(oglasivac.KorisnickoIme) == true)
                {
                    db.OglasivackaAgencijas.Add(oglasivac);
                    db.SaveChanges();
                    ModelState.Clear();
                }
                else
                {
                    ModelState.AddModelError("", "Korisničko ime je zauzeto!");
                    return View();
                }
            }
            var korisnik = db.OglasivackaAgencijas.Where(o => o.KorisnickoIme == oglasivac.KorisnickoIme && o.Lozinka == oglasivac.Lozinka).FirstOrDefault();
            Session["ID"] = korisnik.OglasivackaAgencijaID.ToString();
            Session["KorisnickoIme"] = korisnik.KorisnickoIme.ToString();
            Session["Email"] = korisnik.Email.ToString();
            Session["Status"] = "agencija";
            return RedirectToAction("LoggedIn");
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(OglasivackaAgencija oglasivac)
        {
            var korisnik = db.OglasivackaAgencijas.Where(o => o.KorisnickoIme == oglasivac.KorisnickoIme && o.Lozinka == oglasivac.Lozinka).FirstOrDefault();
            if (korisnik != null)
            {
                Session["ID"] = korisnik.OglasivackaAgencijaID.ToString();
                Session["KorisnickoIme"] = korisnik.KorisnickoIme.ToString();
                Session["Email"] = korisnik.Email.ToString();
                Session["Status"] = "agencija";
                FormsAuthentication.SetAuthCookie(oglasivac.KorisnickoIme, false);
                return RedirectToAction("LoggedIn");
            }
            else
            {
                ModelState.AddModelError("", "Korisničko ime ili lozinka nisu ispravni!");
            }
            return View();
        }

        public ActionResult LoggedIn()
        {
            if (Session["ID"] == null)
            {
                return RedirectToAction("Login");
            }
            else
            {
                if (Session["Status"].ToString() != "agencija")
                {
                    return RedirectToAction("KrivaUloga", "Home");
                }
                else
                {
                    int id = Convert.ToInt32(Session["ID"].ToString());
                    OglasivackaAgencija agencija = db.OglasivackaAgencijas.Find(id);
                    return View(agencija);
                }
            }
        }

        public bool ProvjeraKorisnickogImena(string username)
        {
            bool provjera = true;
            foreach (var item in db.OglasivackaAgencijas)
            {
                if (username == item.KorisnickoIme)
                {
                    provjera = false;
                }
            }
            return provjera;
        }
    }
}

CarCommercial/CarCommercial/Controllers/VlasnikAutasController.cs
using CarCommercial.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace CarCommercial.Controllers
{
    public class VlasnikAutasController : Controller
    {
        private CarCommercialContext db = new CarCommercialContext();

        // GET: VlasnikAutas
        public ActionResult Index()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("ErrorPage", "Home");
            }
            else
            {
                return View(db.VlasnikAutas.ToList());
            }
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(VlasnikAuta vlasnik)
        {
            Session.Clear();
            if (ModelState.IsValid)
            {
                if (ProvjeraKorisnickogImena(vlasnik.KorisnickoIme) == true)
                {
                    db.VlasnikAutas.Add(vlasnik);
                    db.SaveChanges();
                    ModelState.Clear();                    
                }
                else
                {
                    ModelState.AddModelError("", "Korisničko ime je zauzeto!");
                    return View();
                }
            }            
            var korisnik = db.VlasnikAutas.Where(v => v.KorisnickoIme == vlasnik.KorisnickoIme && v.Lozinka == vlasnik.Lozinka).FirstOrDefault();
            Session["ID"] = korisnik.VlasnikAutaID.ToString();
            Session["KorisnickoIme"] = korisnik.KorisnickoIme.ToString();
            Session["Email"] = korisnik.Email.ToString();
            Session["Status"] = "vlasnik";
            return RedirectToAction("LoggedIn");
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(VlasnikAuta vlasnik)
        {
            Session.Clear();
            var korisnik = db.VlasnikAutas.Where(v => v.KorisnickoIme == vlasnik.KorisnickoIme && v.Lozinka == vlasnik.Lozinka).FirstOrDefault();
            if (korisnik != null)
            {
                Session["ID"] = korisnik.VlasnikAutaID.ToString();
                Session["KorisnickoIme"] = korisnik.KorisnickoIme.ToString();
                Session["Email"] = korisnik.Email.ToString();
                Session["Status"] = "vlasnik";
                FormsAuthentication.SetAuthCookie(vlasnik.KorisnickoIme, false);
                return RedirectToAction("LoggedIn");
            }
            else
            {
                ModelState.AddModelError("", "Korisničko ime ili lozinka nisu ispravni!");
            }
            return View();
        }

        public ActionResult LoggedIn()
        {
            if (Session["ID"] == null)
            {
                return RedirectToAction("Login");
            }
            else
            {
                if (Session["Status"].ToString() != "vlasnik")
                {
                    return RedirectToAction("KrivaUloga", "Home");
                }
                else
                {
                    int id = Convert.ToInt32(Session["ID"].ToString());
                    VlasnikAuta vlasnik = db.VlasnikAutas.Find(id);
                    return View(vlasnik);
                }
            }
        }

        public bool ProvjeraKorisnickogImena(string username)
        {
            bool provjera = true;
            foreach (var item in db.VlasnikAutas)
            {
                if (username == item.KorisnickoIme)
                {
                    provjera = false;
                }
            }
            return provjera;
        }
    }
}

CarCommercial/CarCommercial/Views/OglasivackaAgencijas/Index.cshtml
@model IEnumerable<CarCommercial.Models.OglasivackaAgencija>

@{
    ViewBag.Title = "Index";
}

<h2>Popis svih korisnika (Oglašivačke agencije)</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NazivTvrtke)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sjediste)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KorisnickoIme)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NazivTvrtke)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sjediste)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KorisnickoIme)
        </td>        
    </tr>
}

</table>

@if (Session["Status"].ToString() == "vlasnik")
{
    <div>
        <p><input class="btn btn-link" value="Povratak na naslovnicu" readonly onclick="@("window.location.href='" + @Url.Action("LoggedIn", "VlasnikAutas") + "'");" /></p>
    </div>
}
@if (Session["Status"].ToString() == "agencija")
{
    <div>
        <p><input class="btn btn-link" value="Povratak na naslovnicu" readonly onclick="@("window.location.href='" + @Url.Action("LoggedIn", "OglasivackaAgencijas") + "'");" /></p>
    </div>
}

CarCommercial/CarCommercial/Views/OglasivackaAgencijas/LoggedIn.cshtml
@model CarCommercial.Models.OglasivackaAgencija

@{
    ViewBag.Title = "LoggedIn";
}

<h2>@Html.DisplayFor(model => model.KorisnickoIme)</h2>

<div class="row">
    <h4>Moj profil</h4>
    <hr />
    <div class="col-md-7">
        <div>
            
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.NazivTvrtke)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.NazivTvrtke)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Sjediste)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Sjediste)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Email)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Email)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.BrojTelefona)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.BrojTelefona)
                </dd>

            </dl>
        </div>

        <div>
            <p><input class="btn btn-success alert-link" value="Moji oglasi" readonly onclick="@("window.location.href='" + @Url.Action("MojiOglasi", "Oglas") + "'");" /></p>
        </div>

        <div>
            <p><input class="btn btn-success alert-link" value="Moje rezervacije" readonly onclick="@("window.location.href='" + @Url.Action("MojeRezervacijeAgencija", "Rezervacijas") + "'");" /></p>
        </div>
    </div>

    <div class="col-md-offset-6">
        <div>
            <p><input class="btn btn-info alert-link" value="Popis svih vozila" readonly onclick="@("window.location.href='" + @Url.Action("Index", "Automobils") + "'");" /></p>
        </div>

        <div>
            <p><input class="btn btn-info alert-link" value="Popis svih oglasa" readonly onclick="@("window.location.href='" + @Url.Action("Index", "Oglas") + "'");" /></p>
        </div>

        <div>
            <p><input class="btn btn-info alert-link" value="Popis svih vlasnika vozila" readonly onclick="@("window.location.href='" + @Url.Action("Index", "VlasnikAutas") + "'");" /></p>
        </div>

        <div>
            <p><input class="btn btn-info alert-link" value="Popis svih agencija" readonly onclick="@("window.location.href='" + @Url.Action("Index", "OglasivackaAgencijas") + "'");" /></p>
        </div>
    </div>
</div>

@*<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.OglasivackaAgencijaID }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

CarCommercial/CarCommercial/Views/OglasivackaAgencijas/Login.cshtml
@model CarCommercial.Models.OglasivackaAgencija

@{
    ViewBag.Title = "Login";
}

<h2>Prijava</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Agencija za oglašavanje</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.KorisnickoIme, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KorisnickoIme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KorisnickoIme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lozinka, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lozinka, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lozinka, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Prijavi se" class="btn btn-warning active" readonly />
            </div>
        </div>
    </div>
}

<div>
    <p><input class="btn btn-link" value="Povratak na naslovnicu" readonly onclick="@("window.location.href='" + @Url.Action("Index", "Home") + "'");" /></p>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CarCommercial/CarCommercial/Views/OglasivackaAgencijas/Register.cshtml
@model CarCommercial.Models.OglasivackaAgencija

@{
    ViewBag.Title = "Register";
}

<h2>Registracija</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Agencija za oglašavanje</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.NazivTvrtke, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NazivTvrtke, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NazivTvrtke, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sjediste, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sjediste, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sjediste, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KorisnickoIme, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KorisnickoIme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KorisnickoIme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lozinka, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lozinka, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lozinka, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PotvrdaLozinke, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PotvrdaLozinke, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PotvrdaLozinke, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrojTelefona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrojTelefona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrojTelefona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registriraj se" class="btn btn-warning active" readonly />
            </div>
        </div>
    </div>
}

<div>
    <p><input class="btn btn-link" value="Povratak na naslovnicu" readonly onclick="@("window.location.href='" + @Url.Action("Index", "Home") + "'");" /></p>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}